### ISSUE TITLE
組み込み関数の翻訳リンクが多数 404 状態です

### ISSUE THREAD

**Issue by tettekete** [jpa-perl/perldoc.jp#12]
組み込み関数の翻訳リンクが多数 404 状態です。

**場所:**

- [“Perlの組み込み関数の翻訳一覧 - perldoc.jp”](http://perldoc.jp/index/function)

**一覧:**

`m`,`map`,`mkdir`,`msgctl`,`msgget`,`msgrcv`,`msgsnd`,`my`,`q/STRING/`,`qq`,`qr`,`quotemeta`,`qw/STRING/`,`qx/STRING/`,`s`,`say`,`scalar`,`seek`,`seekdir`,`select`,`semctl`,`semget`,`semop`,`send`,`setgrent`,`sethostent`,`setnetent`,`setpgrp`,`setpriority`,`setprotoent`,`setpwent`,`setservent`,`setsockopt`,`shift`,`shmctl`,`shmget`,`shmread`,`shmwrite`,`shutdown`,`sin`,`sleep`,`socket`,`socketpair`,`sort`,`splice`,`split`,`sprintf`,`sqrt`,`srand`,`stat`,`state`,`study`,`sub`,`substr`,`symlink`,`syscall`,`syscall`,`sysopen`,`sysread`,`sysread`,`sysseek`,`sysseek`,`system`,`syswrite`,`syswrite`,`tr`,`truncate`

**`curl` アクセステスト例:**

```bash
$ curl -s --head https://perldoc.jp/func/quotemeta
HTTP/2 404 
date: Mon, 06 Jun 2022 04:14:56 GMT
content-type: text/html; charset=UTF-8
cf-cache-status: DYNAMIC
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=GuopAkGwJtNWbICwJe%2BGedj6GLeErQkgnIGK%2B2%2Befd%2BUqVjwoWBb39RU4KymirzIQD%2B7Kc4XvZNzwi%2FJC7py1NQbS%2FavaeDvnxBA%2B8S7Z5bFCj4nm4xZTTzCiIra"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 716e52f11aa03408-NRT
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
```

**Comment by xtetsuji** [comment]
@tettekete ご報告ありがとうございます。システム側のアクセス権限を持っている担当と連携して調査します。

**Comment by ktat** [comment]
@xtetsuji @karupanerura ↑の修正で、通常の関数は大丈夫になったようですが、`s` とか`qr`が駄目なままですね。僕の手元だとうまく動いているので、モジュールのバージョンのせいかもしれません。

関係しそうなのは、Pod::Perldocくらいですかね,,,。手元のバージョンは、3.28になります。

**Comment by karupanerura** [comment]
@ktat ありがとうございます！おっしゃるとおり古いようでした。バージョンアップしたところ問題は解消したように見えます。
