### ISSUE TITLE
「Perlのコアドキュメントの翻訳一覧」の内容が古い

### ISSUE THREAD

**Issue by argrath** [jpa-perl/perldoc.jp#23]
ナビゲーションの「本体」を押すと[Perlのコアドキュメントの翻訳一覧 - perldoc.jp](http://perldoc.jp/index/core) が表示されますが、内容が古いようです(5.16の頃のもの?)

**Comment by ktat** [comment]
@argrath このファイルから作っているので、これを編集したら良さそうです。
https://github.com/jpa-perl/perldoc.jp/blob/master/toc.txt

**Comment by ktat** [comment]
@argrath 対応しました。

**Comment by karupanerura** [comment]
なるほど。背景含め理解しました。ありがとうございます！
#25 をマージしたところ解消したように見えます。

もしまだ同様の問題があればreopenしてください。
