### ISSUE TITLE
関数単体ページ内のリンクが機能していない

### ISSUE THREAD

**Issue by argrath** [jpa-perl/perldoc.jp#24]
ナビゲーションの「関数」からたどった関数単体ページ内のリンクが機能していません。

例えば [Perlの組み込み関数 my の翻訳 - perldoc.jp](http://perldoc.jp/func/my) のページには `eval` や `undef` へのリンクがありますが、選択しても当該関数のページに移動しません。

**Comment by ktat** [comment]
`L<undef|/undef EXPR>` 書式の場合の対応ができていないというか、そもそも、

**Comment by karupanerura** [comment]
なるほど。anchorで `/undef#EXPR` みたいに飛べるようにするとかだと手軽かもですね。（本当にそれですべてのケースに対応できるのか調べられていませんが。。）

こちらも #26 を取り込んだところ問題は解消されたように思えます。
ありがとうございました！もしまだ同様の問題あればreopenしていただけますと幸いです。

**Comment by ktat** [comment]
@karupanerura 追加修正しました。
https://github.com/jpa-perl/perldoc.jp/pull/28
