### ISSUE TITLE
「最近の更新」にJPRP側の更新が反映されていない

### ISSUE THREAD

**Issue by argrath** [jpa-perl/perldoc.jp#32]
http://perldoc.jp/ の「最近の更新」部分にJPRP側の更新が反映されていないようです。

例えば http://perldoc.jp/docs/modules/IO-Socket-SSL-1.33/SSL.pod は 2023-03-05 に更新していますが反映されていません。
個別ページのレンダリング自体は問題なさそうです。

(この項目がそもそも必要かという話もありますがそれはさておき…)

**Comment by kfly8** [comment]
JPRPだけでなく、module-pod-jpの方も更新されていなさそうですねー。
見てみます。

**Comment by kfly8** [comment]
反映されるようになりました。

<img width="821" alt="image" src="https://github.com/jpa-perl/perldoc.jp/assets/722500/49e07718-aef5-4107-a1c7-c4b987fed67b">
