### ISSUE TITLE
記事によって文字化けが生じている

### ISSUE THREAD

**Issue by tani-ro-hei** [jpa-perl/perldoc.jp#4]
組込関数の翻訳の個別ページが、ここ近日、だいたい文字化けしてしまっています。
例: [https://perldoc.jp/func/print](https://perldoc.jp/func/print)

ソースを見てもエンコードが混在してしまっている感じで、よくわからない状態のようです。

**Comment by Nagatosi** [comment]
おおもとの perlfunc.pod には問題ないのでこちらのサイト転記する際の設定の問題と思われます。perlfunc.pod をUTF-8 以外の文字コードとして読み込んだうえで UTF-8 に変換しているように見えます。こちらはよく使わせていただいていたので、早く回復していただけるとありがたいです。

**Comment by tani-ro-hei** [comment]
組込関数については解消しているようですが、変数のページはまだ（なのか新たに、なのか定かではありませんが）文字化けしているようですね。
例: [https://perldoc.jp/variable/%40ARGV](https://perldoc.jp/variable/%40ARGV)

**Comment by karupanerura** [comment]
ありがとうございます。 #5 #11 で対応しました。
