### ISSUE TITLE
`-M<number>` が、`-number` と表示されてしまっている

### ISSUE THREAD

**Issue by ktat** [jpa-perl/perldoc.jp#7]
下記で報告されている事象になります。
https://osdn.net/projects/perldocjp/ticket/35001　

手元で再現しないので、サーバーのモジュールのバージョンが古いとかいう原因と思われます。

該当のURLは下記です。
https://perldoc.jp/docs/modules/CGI-SpeedyCGI-2.21/SpeedyCGI.pod#pod21033-29992-12391-12365-12427-12458-12503-12471-12519-12531

の、BufsizGet のところです。

**Comment by ktat** [comment]
MaxBackends もでした。

@karupanerura HTML::Parser のバージョンを上げれば解消するかと思います。

HTML-Parser-3.69 で再現しました。

Pod::Simple も古ければ上げておいて良いかと思います。

**Comment by karupanerura** [comment]
ありがとうございます！対応しました
